# Change these first
owner: darespider # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Glances
    url: https://glances.darespider.family
  - name: Raspberry PI Monitor
    url: https://rpi.darespider.family
  - name: Homer
    url: https://homer.darespider.family
  - name: Jellyfin
    url: https://jellyfin.darespider.family
  - name: Kavita
    url: https://kavita.darespider.family
  - name: Komga
    url: https://komga.darespider.family
  - name: Portainer
    url: https://portainer.darespider.family
  - name: Pyload
    url: https://pyload.darespider.family
  - name: Transmission
    url: https://transmission.darespider.family
  - name: Syncthing
    url: https://syncthing.darespider.family
  - name: Vaultwarden
    url: https://vaultwarden.darespider.family
    
assignees: # Users to assign downtime issues (optional)
  - rurickdev

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.darespider.family
  #baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
